"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { BrandLogo } from "@/components/BrandLogo";
import { api, setToken } from "@/lib/api";
export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setLoading(true); const form = new FormData(e.currentTarget); const body: Record<string,string> = Object.fromEntries(form.entries()) as Record<string,string>; try { const data = await api<{access_token:string}>(mode === "login" ? "/api/auth/login" : "/api/auth/register", { method: "POST", body: JSON.stringify(body) }); setToken(data.access_token); router.push("/dashboard"); } catch (err) { setError(err instanceof Error ? err.message : "Request failed"); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="card mx-auto max-w-md space-y-5 rounded-[28px] p-8"><BrandLogo textClassName="text-2xl" /><div><p className="eyebrow">{mode === "login" ? "Secure access" : "New workspace"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{mode === "login" ? "Log in to ClusterSage" : "Create your ClusterSage workspace"}</h1><p className="mt-2 section-copy">Sign in to review cluster health, investigate incidents, and manage agent access for your organization.</p></div>{mode === "register" && <><div><label className="mb-2 block text-sm font-medium muted" htmlFor="full_name">Full name</label><input className="input" id="full_name" name="full_name" placeholder="Jane Patel" /></div><div><label className="mb-2 block text-sm font-medium muted" htmlFor="organization_name">Organization name</label><input className="input" id="organization_name" name="organization_name" placeholder="Northwind Platform" required /></div></>}<div><label className="mb-2 block text-sm font-medium muted" htmlFor="email">Email</label><input className="input" id="email" name="email" type="email" placeholder="you@company.com" required /></div><div><label className="mb-2 block text-sm font-medium muted" htmlFor="password">Password</label><input className="input" id="password" name="password" type="password" placeholder="Minimum 8 characters" required minLength={8} /></div>{error && <p className="status-chip status-chip-danger rounded-2xl px-4 py-3 text-sm">{error}</p>}<button className="btn w-full" disabled={loading}>{loading ? "Working..." : mode === "login" ? "Log in" : "Create workspace"}</button></form>;
}
